# Generated by Django 6.0.4 on 2026-07-15 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.email'),
        ),
    ]
